// Datasets for the Map demo page + a Supercluster index per dataset.
//
// A dataset is "N points with coordinates, a category and some details". Two exist:
//   synthetic  500k fabricated points around European cities (instant, deterministic)
//   sgp        ~120k REAL geological samples from sgp-search.io (downloaded on first use)
//
// Every dataset is loaded lazily (the first request that needs it triggers loading) and then
// kept in memory. The expensive derived structures are also built lazily and memoised:
//   * the Supercluster index (server-side clustering by bbox + zoom),
//   * the binary blob (all points as typed arrays, for the "all points on the GPU" mode).

import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import Supercluster from "supercluster";
import type { PointFeature } from "supercluster";
import { POINT_CATEGORIES, POINTS_TOTAL } from "@app/shared";
import type { PointDatasetId, PointDetails, PointMeta } from "@app/shared";

export interface Dataset {
  id: PointDatasetId;
  label: string;
  source: string;
  count: number;
  categoryNames: string[];
  lngLat: Float32Array; // [lng0, lat0, lng1, lat1, ...]  (array index i <=> point id i + 1)
  categories: Uint8Array; // per point: index into categoryNames
  details(id: number): PointDetails | null;
  // memoised derived data
  index?: Supercluster<Props>;
  binary?: Buffer;
}

type Props = { id: number };

// ---- loading / caching ------------------------------------------------------------------

const loaders: Record<PointDatasetId, () => Promise<Dataset>> = {
  synthetic: async () => buildSynthetic(),
  sgp: buildSgp,
};

// Cache the PROMISE, not the result: concurrent first requests share one load instead of
// each downloading 35 MB. A failed load is dropped from the cache so the next request retries.
const loaded = new Map<PointDatasetId, Promise<Dataset>>();

export function loadDataset(id: PointDatasetId): Promise<Dataset> {
  let p = loaded.get(id);
  if (!p) {
    p = loaders[id]();
    loaded.set(id, p);
    p.catch(() => loaded.delete(id));
  }
  return p;
}

export function datasetMeta(ds: Dataset): PointMeta {
  return { dataset: ds.id, label: ds.label, source: ds.source, total: ds.count, categories: ds.categoryNames };
}

// ---- synthetic dataset ------------------------------------------------------------------

// [lng, lat, spread in degrees, weight] — points are drawn around these "cities"
const CITIES: [number, number, number, number][] = [
  [30.52, 50.45, 0.25, 5], // Kyiv
  [21.01, 52.23, 0.2, 4], // Warsaw
  [13.4, 52.52, 0.25, 5], // Berlin
  [2.35, 48.86, 0.25, 6], // Paris
  [-0.12, 51.51, 0.3, 7], // London
  [-3.7, 40.42, 0.25, 4], // Madrid
  [12.5, 41.9, 0.2, 4], // Rome
  [28.98, 41.01, 0.3, 6], // Istanbul
  [37.62, 55.75, 0.35, 6], // Moscow
  [18.07, 59.33, 0.2, 2], // Stockholm
  [16.37, 48.21, 0.2, 3], // Vienna
  [23.72, 37.98, 0.2, 3], // Athens
  [4.9, 52.37, 0.15, 3], // Amsterdam
  [-6.26, 53.35, 0.15, 2], // Dublin
  [24.1, 56.95, 0.15, 2], // Riga
];

/** mulberry32: tiny seeded PRNG, returns a function giving floats in [0, 1). */
function prng(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Everything is a pure function of the point id (seeded PRNG), so details can be recomputed
// on demand and nothing needs storing besides the compact coordinate arrays.
function buildSynthetic(): Dataset {
  const rand = prng(42);
  const gauss = () => Math.sqrt(-2 * Math.log(1 - rand())) * Math.cos(2 * Math.PI * rand());
  const totalWeight = CITIES.reduce((s, c) => s + c[3], 0);

  const lngLat = new Float32Array(POINTS_TOTAL * 2);
  const categories = new Uint8Array(POINTS_TOTAL);
  for (let i = 0; i < POINTS_TOTAL; i++) {
    if (rand() < 0.85) {
      // pick a city proportionally to its weight, then scatter around it
      let r = rand() * totalWeight;
      let city = CITIES[0];
      for (const c of CITIES) { if ((r -= c[3]) < 0) { city = c; break; } }
      lngLat[i * 2] = city[0] + gauss() * city[2] * 1.4; // *1.4: degrees of longitude are "shorter" at this latitude
      lngLat[i * 2 + 1] = city[1] + gauss() * city[2];
    } else {
      // 15% uniform noise across the whole region so empty areas aren't empty
      lngLat[i * 2] = -10 + rand() * 50;
      lngLat[i * 2 + 1] = 36 + rand() * 25;
    }
    categories[i] = Math.floor(rand() * POINT_CATEGORIES.length);
  }

  return {
    id: "synthetic",
    label: "Synthetic points",
    source: "generated by the server (seeded PRNG)",
    count: POINTS_TOTAL,
    categoryNames: [...POINT_CATEGORIES],
    lngLat,
    categories,
    details(id) {
      if (!Number.isInteger(id) || id < 1 || id > POINTS_TOTAL) return null;
      return {
        id,
        name: `Point #${id}`,
        category: POINT_CATEGORIES[categories[id - 1]],
        lng: lngLat[(id - 1) * 2],
        lat: lngLat[(id - 1) * 2 + 1],
        fields: { value: ((id * 7919) % 100000) / 100 },
      };
    },
  };
}

// ---- SGP dataset (real data) ------------------------------------------------------------
// SGP = Sedimentary Geochemistry and Paleoenvironments Project (https://sgp-search.io).
// Its web app loads every sample for the map in ONE response (~35 MB JSON, ~126k records;
// the page/count parameters are ignored for type "samples"). We do the same request once,
// keep a copy on disk, and from then on serve it to the browser in a compact form.

const SGP_URL = "https://sgp-search.io/api/frontend/map";
const SGP_BODY = {
  type: "samples",
  filters: {},
  show: ["section_name", "height_meters", "site_type", "country", "basin_type", "meta_bin", "strat_unit",
    "environment_bin", "geol_age", "lithology_name", "interpreted_age", "min_age", "max_age"],
  page: 0,
  count: 25,
  sorted: [{ id: "sample identifier", desc: false }],
};
const SGP_CACHE_FILE = path.resolve(__dirname, "../../.cache/sgp-samples.json");
const SGP_MAX_AGE_MS = 7 * 24 * 3600 * 1000; // refresh the disk copy weekly

// The most common lithologies get their own color; everything else shares the last slot.
const SGP_CATEGORIES = ["shale", "mudstone", "sandstone", "limestone", "other / unknown"];

interface SgpRecord {
  "sample identifier": number;
  "sample original name": string | null;
  "section name": string | null;
  "interpreted age": string | null;
  "lithology name": string | null;
  "stratigraphic unit": string | null;
  "site longitude": string | null;
  "site latitude": string | null;
}

async function fetchSgpRecords(): Promise<SgpRecord[]> {
  // 1) disk cache
  try {
    const st = await stat(SGP_CACHE_FILE);
    if (Date.now() - st.mtimeMs < SGP_MAX_AGE_MS) {
      console.log("[points] SGP: reading cached copy from disk");
      return JSON.parse(await readFile(SGP_CACHE_FILE, "utf8"));
    }
  } catch {
    // no cache yet
  }
  // 2) download
  console.log("[points] SGP: downloading from sgp-search.io (~35 MB)...");
  const res = await fetch(SGP_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json" },
    body: JSON.stringify(SGP_BODY),
    signal: AbortSignal.timeout(120_000),
  });
  if (!res.ok) throw new Error(`sgp-search.io answered HTTP ${res.status}`);
  const text = await res.text();
  const records = JSON.parse(text) as SgpRecord[];
  // best effort: a failure to write the cache must not fail the request
  try {
    await mkdir(path.dirname(SGP_CACHE_FILE), { recursive: true });
    await writeFile(SGP_CACHE_FILE, text);
  } catch (e) {
    console.warn("[points] SGP: could not write the disk cache", e);
  }
  return records;
}

async function buildSgp(): Promise<Dataset> {
  const t0 = performance.now();
  const records = (await fetchSgpRecords()).filter((r) => {
    const lng = Number(r["site longitude"]);
    const lat = Number(r["site latitude"]);
    // ~4% of samples have no coordinates — they cannot be put on a map
    return r["site longitude"] != null && r["site latitude"] != null && Number.isFinite(lng) && Number.isFinite(lat);
  });

  const count = records.length;
  const lngLat = new Float32Array(count * 2);
  const categories = new Uint8Array(count);
  for (let i = 0; i < count; i++) {
    const r = records[i];
    lngLat[i * 2] = Number(r["site longitude"]);
    lngLat[i * 2 + 1] = Number(r["site latitude"]);
    const k = SGP_CATEGORIES.indexOf(r["lithology name"] ?? "");
    categories[i] = k >= 0 ? k : SGP_CATEGORIES.length - 1;
  }
  console.log(`[points] SGP: ${count} samples with coordinates ready in ${(performance.now() - t0).toFixed(0)} ms`);

  return {
    id: "sgp",
    label: "SGP geological samples",
    source: "sgp-search.io (Sedimentary Geochemistry and Paleoenvironments Project)",
    count,
    categoryNames: SGP_CATEGORIES,
    lngLat,
    categories,
    details(id) {
      const r = Number.isInteger(id) ? records[id - 1] : undefined;
      if (!r) return null;
      return {
        id,
        name: r["sample original name"] ?? `Sample ${r["sample identifier"]}`,
        category: r["lithology name"] ?? "unknown",
        lng: lngLat[(id - 1) * 2],
        lat: lngLat[(id - 1) * 2 + 1],
        fields: {
          "sample id": r["sample identifier"],
          section: r["section name"],
          "stratigraphic unit": r["stratigraphic unit"],
          "age (Ma)": r["interpreted age"] == null ? null : Number(r["interpreted age"]),
        },
      };
    },
  };
}

// ---- derived structures -----------------------------------------------------------------

// Supercluster builds a hierarchy of clusters, one level per zoom, on top of a KD-tree.
// Building is the expensive part (seconds for 500k points); a query (bbox + zoom) is
// milliseconds. So: build once per dataset, lazily, and share the instance between requests.
export function getIndex(ds: Dataset): Supercluster<Props> {
  if (ds.index) return ds.index;
  const t0 = performance.now();
  const features: PointFeature<Props>[] = new Array(ds.count);
  for (let i = 0; i < ds.count; i++) {
    features[i] = {
      type: "Feature",
      properties: { id: i + 1 },
      geometry: { type: "Point", coordinates: [ds.lngLat[i * 2], ds.lngLat[i * 2 + 1]] },
    };
  }
  // radius: clustering distance in px (at 512px tiles); maxZoom: beyond it every point is separate
  ds.index = new Supercluster<Props>({ radius: 60, maxZoom: 16, minPoints: 2 }).load(features);
  console.log(`[points] ${ds.id}: Supercluster index for ${ds.count} points built in ${(performance.now() - t0).toFixed(0)} ms`);
  return ds.index;
}

/** All points as one binary blob: Float32 [lng,lat]*N followed by Uint8 category*N. */
export function getBinary(ds: Dataset): Buffer {
  return (ds.binary ??= Buffer.concat([Buffer.from(ds.lngLat.buffer), Buffer.from(ds.categories.buffer)]));
}
