// Demo: showing hundreds of thousands of geo points with their own data on a map.
// All the interesting logic lives in lib/map/PointsMap.ts; this page only wires it to React.

import { Fragment, useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { PointsMap } from "@/lib/map/PointsMap";
import type { MapStats, Mode } from "@/lib/map/PointsMap";
import type { Provider } from "@/lib/map/basemap";
import { useFps } from "@/lib/useFps";
import type { PointDatasetId, PointDetails, PointMeta } from "@app/shared";

// Optional. Without it the page falls back to MapLibre (free, no key needed).
const GOOGLE_KEY = import.meta.env.VITE_GOOGLE_MAPS_API_KEY as string | undefined;

const MODES: { id: Mode; label: string; hint: string }[] = [
  { id: "clusters", label: "Server clusters", hint: "API returns only the visible viewport, pre-clustered" },
  { id: "gpu", label: "deck.gl all points", hint: "all points downloaded once, drawn on the GPU" },
  { id: "markers", label: "DOM markers", hint: "one DOM element per point — the slow way" },
];
const DATASETS: { id: PointDatasetId; label: string; hint: string }[] = [
  { id: "synthetic", label: "Synthetic 500k", hint: "generated by the server, instant" },
  { id: "sgp", label: "SGP real samples", hint: "geological samples from sgp-search.io; the first load downloads ~35 MB on the server" },
];

// Same order/colors as PALETTE in PointsMap.ts (category index -> color)
const CATEGORY_COLORS = ["rgb(220,38,38)", "rgb(37,99,235)", "rgb(22,163,74)", "rgb(202,138,4)", "rgb(147,51,234)"];

const MARKER_LIMITS = [500, 2_000, 5_000, 10_000];

export default function MapPage() {
  const host = useRef<HTMLDivElement>(null);
  const map = useRef<PointsMap | null>(null);
  const [provider, setProvider] = useState<Provider>(GOOGLE_KEY ? "google" : "maplibre");
  // The starting mode/dataset can be given in the URL (/map?mode=gpu&dataset=sgp) — handy for sharing and testing.
  const [params] = useSearchParams();
  const initialMode = MODES.find((m) => m.id === params.get("mode"))?.id ?? "clusters";
  const [mode, setMode] = useState<Mode>(initialMode);
  const [markerLimit, setMarkerLimit] = useState(2_000);
  const [dataset, setDataset] = useState<PointDatasetId>(
    DATASETS.find((d) => d.id === params.get("dataset"))?.id ?? "synthetic",
  );
  const [meta, setMeta] = useState<PointMeta | null>(null);
  const [ready, setReady] = useState(false);
  const [stats, setStats] = useState<MapStats | null>(null);
  const [selected, setSelected] = useState<PointDetails | null>(null);
  const [error, setError] = useState<string | null>(null);
  const fps = useFps();

  // (Re)create the map whenever the provider changes. The container div is keyed by provider
  // below, so each provider gets a fresh DOM node (Google and MapLibre can't share one).
  useEffect(() => {
    let cancelled = false;
    let instance: PointsMap | null = null;
    setReady(false);
    setError(null);
    setSelected(null);
    setMeta(null);

    PointsMap.create(host.current!, {
      provider,
      googleKey: GOOGLE_KEY,
      // the controller starts in the current UI state; later changes arrive via the effects below
      dataset,
      mode,
      markerLimit,
      onMeta: setMeta,
      onStats: setStats,
      onSelect: setSelected,
      onError: setError,
    })
      .then((pm) => {
        // The effect may have been cleaned up while the map was still loading (provider switched,
        // React StrictMode remount): then this instance is already unwanted.
        if (cancelled) return pm.dispose();
        instance = pm;
        map.current = pm;
        setReady(true);
      })
      .catch((e) => !cancelled && setError(e instanceof Error ? e.message : "Failed to create the map"));

    return () => {
      cancelled = true;
      instance?.dispose();
      map.current = null;
    };
    // `dataset`/`mode`/`markerLimit` are deliberately NOT dependencies: changing them must not
    // rebuild the whole map, they are pushed into the existing controller instead.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [provider]);

  // Push UI state into the controller once it exists.
  useEffect(() => { if (ready) map.current?.setMode(mode); }, [ready, mode]);
  useEffect(() => { if (ready) map.current?.setMarkerLimit(markerLimit); }, [ready, markerLimit]);
  useEffect(() => {
    if (ready) { setError(null); map.current?.setDataset(dataset); }
  }, [ready, dataset]);

  const btn = (active: boolean, disabled = false) =>
    `rounded-md px-3 py-1.5 ${active ? "bg-slate-900 text-white" : "bg-slate-100 hover:bg-slate-200"} ${disabled ? "opacity-40 pointer-events-none" : ""}`;

  return (
    <div className="flex h-[calc(100vh-56px)] flex-col">
      <div className="flex flex-wrap items-center gap-2 border-b p-3 text-sm">
        <span className="text-slate-500">Map:</span>
        <button className={btn(provider === "google", !GOOGLE_KEY)} onClick={() => setProvider("google")} title={GOOGLE_KEY ? "" : "Set VITE_GOOGLE_MAPS_API_KEY in client/.env"}>
          Google Maps
        </button>
        <button className={btn(provider === "maplibre")} onClick={() => setProvider("maplibre")}>
          MapLibre
        </button>
        {!GOOGLE_KEY && <span className="text-xs text-amber-600">no VITE_GOOGLE_MAPS_API_KEY — Google disabled</span>}

        <span className="ml-4 text-slate-500">Data:</span>
        {DATASETS.map((d) => (
          <button key={d.id} className={btn(dataset === d.id)} onClick={() => setDataset(d.id)} title={d.hint}>
            {d.label}
          </button>
        ))}

        <span className="ml-4 text-slate-500">Render:</span>
        {MODES.map((m) => (
          <button key={m.id} className={btn(mode === m.id)} onClick={() => setMode(m.id)} title={m.hint}>
            {m.label}
          </button>
        ))}
        {mode === "markers" && (
          <>
            <span className="text-slate-500">markers:</span>
            {MARKER_LIMITS.map((n) => (
              <button key={n} className={btn(markerLimit === n)} onClick={() => setMarkerLimit(n)}>
                {n.toLocaleString()}
              </button>
            ))}
          </>
        )}
      </div>

      <div className="relative min-h-0 flex-1">
        {/* key => a brand-new DOM node per provider */}
        <div key={provider} ref={host} className="h-full w-full" />

        <pre className="pointer-events-none absolute left-3 top-3 rounded bg-black/65 p-2 text-xs leading-5 text-slate-100">
{`provider   ${provider}
dataset    ${meta?.dataset === dataset ? meta.label : dataset}${stats?.total ? ` (${stats.total.toLocaleString()})` : ""}
mode       ${mode}
drawn      ${stats ? stats.drawn.toLocaleString() : "–"}${stats?.loading ? "  (loading…)" : ""}
fetch      ${stats?.lastFetchMs ? `${stats.lastFetchMs.toFixed(0)} ms` : "–"}${stats?.lastBytes ? ` · ${(stats.lastBytes / 1024).toFixed(0)} KB` : ""}
main-thread FPS ${fps}`}
        </pre>

        {stats?.loadingDataset && (
          <div className="absolute inset-x-0 top-3 mx-auto w-fit max-w-md rounded bg-amber-100 px-3 py-2 text-center text-sm text-amber-900 shadow">
            Server is loading “{dataset}”… The first load of the SGP data downloads ~35 MB from sgp-search.io
            (it can take about a minute); after that it is cached on the server's disk.
          </div>
        )}

        {meta?.dataset === dataset && (
          <div className="absolute bottom-8 left-3 rounded bg-white/90 p-2 text-xs shadow">
            <div className="mb-1 font-semibold">{meta.label}</div>
            {meta.categories.map((name, i) => (
              <div key={name} className="flex items-center gap-1.5">
                <span className="inline-block h-2.5 w-2.5 rounded-full" style={{ background: CATEGORY_COLORS[i] }} />
                {name}
              </div>
            ))}
            <div className="mt-1 max-w-48 text-[10px] text-slate-400">{meta.source}</div>
          </div>
        )}

        {!ready && !error && <div className="absolute inset-0 grid place-items-center bg-white/60 text-sm text-slate-600">loading map…</div>}
        {error && <div className="absolute inset-x-3 bottom-3 rounded bg-red-600 p-2 text-sm text-white">{error}</div>}

        {selected && (
          <div className="absolute right-3 top-3 w-60 rounded bg-white p-3 text-sm shadow-lg">
            <div className="flex items-start justify-between">
              <b>{selected.name}</b>
              <button onClick={() => setSelected(null)} className="text-slate-400 hover:text-slate-700">✕</button>
            </div>
            <dl className="mt-2 grid grid-cols-[auto_1fr] gap-x-3 gap-y-1 text-slate-600">
              <dt>category</dt><dd>{selected.category}</dd>
              <dt>lng, lat</dt><dd className="tabular-nums">{selected.lng.toFixed(4)}, {selected.lat.toFixed(4)}</dd>
              {/* dataset-specific fields: the server decides which ones exist */}
              {Object.entries(selected.fields).map(([k, v]) => (
                <Fragment key={k}>
                  <dt>{k}</dt>
                  <dd className="break-words">{v ?? "–"}</dd>
                </Fragment>
              ))}
            </dl>
            <p className="mt-2 text-xs text-slate-400">loaded on click from /api/points/:id</p>
          </div>
        )}
      </div>
    </div>
  );
}
